<?php

namespace Database\Seeders;

use App\Models\Plant;
use App\Models\Tag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class CompletePlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Données de 30 plantes diversifiées avec classification botanique
        $plants = [
            // 1. Phalaenopsis amabilis (Orchidée papillon)
            [
                'name' => 'Orchidée papillon',
                'family' => 'Orchidaceae',
                'subfamily' => 'Epidendroideae',
                'genus' => 'Phalaenopsis',
                'species' => 'amabilis',
                'cultivar' => 'White Dream',
                'scientific_name' => 'Phalaenopsis amabilis',
                'description' => 'Orchidée élégante avec fleurs blanches délicates. Plante tropicale très prisée pour son adaptation à la culture en intérieur.',
                'purchase_date' => '10/03/2023',
                'purchase_place' => 'Jardinerie locale',
                'location' => 'Windowsill salon',
                'light_requirement' => 4,
                'temperature_min' => 18,
                'temperature_max' => 24,
                'humidity_level' => 60,
                'watering_frequency' => 2,
                'soil_type' => 'Écorce de pin (orchidée)',
                'difficulty_level' => 3,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Tropical', 'Floraison', 'Orchidée'],
            ],
            // 2. Monstera deliciosa
            [
                'name' => 'Monstera deliciosa',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Monstera',
                'species' => 'deliciosa',
                'scientific_name' => 'Monstera deliciosa',
                'description' => 'Grande feuille percée caractéristique. Plante grimpante classique pour la décoration intérieure.',
                'purchase_date' => '05/01/2023',
                'location' => 'Coin salon',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 50,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau riche',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Feuillage', 'Facile', 'Grand format'],
            ],
            // 3. Sansevieria trifasciata
            [
                'name' => 'Sansevieria',
                'family' => 'Asparagaceae',
                'subfamily' => 'Nolinoideae',
                'genus' => 'Sansevieria',
                'species' => 'trifasciata',
                'variety' => 'Laurentii',
                'scientific_name' => 'Sansevieria trifasciata',
                'description' => 'Plante très résistante avec feuilles pointues. Parfaite pour les débutants, tolère l\'ombre.',
                'purchase_date' => '12/05/2022',
                'location' => 'Bureau',
                'light_requirement' => 2,
                'temperature_min' => 10,
                'temperature_max' => 25,
                'humidity_level' => 40,
                'watering_frequency' => 4,
                'soil_type' => 'Terreau cactus',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_outdoor' => true,
                'is_toxic' => true,
                'tags' => ['Succulente', 'Très facile', 'Épuratrice d\'air'],
            ],
            // 4. Rhaphidophora tetrasperma
            [
                'name' => 'Mini Monstera',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Rhaphidophora',
                'species' => 'tetrasperma',
                'scientific_name' => 'Rhaphidophora tetrasperma',
                'description' => 'Version miniature de Monstera avec feuilles fenêtrées délicates. Croissance compacte.',
                'purchase_date' => '20/06/2023',
                'location' => 'Étagère cuisine',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 24,
                'humidity_level' => 55,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau universel léger',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'tags' => ['Feuillage', 'Compact', 'Moderne'],
            ],
            // 5. Pothos aureus
            [
                'name' => 'Pothos doré',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Epipremnum',
                'species' => 'aureum',
                'scientific_name' => 'Epipremnum aureum',
                'description' => 'Plante grimpante très populaire avec feuilles vertes dorées. Excellent pour les murs.',
                'purchase_date' => '08/02/2023',
                'location' => 'Étagère murale',
                'light_requirement' => 2,
                'temperature_min' => 12,
                'temperature_max' => 25,
                'humidity_level' => 45,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau universel',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Plante grimpante', 'Très facile', 'Purifiante'],
            ],
            // 6. Calathea ornata
            [
                'name' => 'Calathea rayée',
                'family' => 'Marantaceae',
                'subfamily' => 'Calatheoideae',
                'genus' => 'Calathea',
                'species' => 'ornata',
                'scientific_name' => 'Calathea ornata',
                'description' => 'Feuilles vert foncé avec rayures roses. Apprécie l\'humidité élevée et l\'ombre.',
                'purchase_date' => '15/04/2023',
                'location' => 'Salle de bain',
                'light_requirement' => 2,
                'temperature_min' => 18,
                'temperature_max' => 25,
                'humidity_level' => 70,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau riche et aéré',
                'difficulty_level' => 3,
                'is_indoor' => true,
                'tags' => ['Feuillage coloré', 'Humidité', 'Tropical'],
            ],
            // 7. Anthurium andraeanum
            [
                'name' => 'Anthurium rouge',
                'family' => 'Araceae',
                'subfamily' => 'Aroideae',
                'genus' => 'Anthurium',
                'species' => 'andraeanum',
                'scientific_name' => 'Anthurium andraeanum',
                'description' => 'Fleurs rouges brillantes en forme de cœur. Floraison longue toute l\'année.',
                'purchase_date' => '01/07/2023',
                'location' => 'Salon',
                'light_requirement' => 3,
                'temperature_min' => 18,
                'temperature_max' => 28,
                'humidity_level' => 60,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau orchidée',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Floraison', 'Rouge', 'Longue floraison'],
            ],
            // 8. Ficus lyrata
            [
                'name' => 'Figuier lyre',
                'family' => 'Moraceae',
                'subfamily' => 'Moreae',
                'genus' => 'Ficus',
                'species' => 'lyrata',
                'scientific_name' => 'Ficus lyrata',
                'description' => 'Grandes feuilles en forme de lyre, très décoratives. Nécessite beaucoup d\'espace.',
                'purchase_date' => '22/08/2022',
                'location' => 'Coin séjour',
                'light_requirement' => 4,
                'temperature_min' => 15,
                'temperature_max' => 24,
                'humidity_level' => 50,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau riche',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'max_height' => 180,
                'tags' => ['Grand format', 'Feuillage', 'Tendance'],
            ],
            // 9. Alocasia macrorrhiza
            [
                'name' => 'Alocasia géante',
                'family' => 'Araceae',
                'subfamily' => 'Aroideae',
                'genus' => 'Alocasia',
                'species' => 'macrorrhiza',
                'scientific_name' => 'Alocasia macrorrhiza',
                'description' => 'Énormes feuilles vert foncé avec nervures claires. Aspect tropical spectaculaire.',
                'purchase_date' => '10/03/2023',
                'location' => 'Entrée',
                'light_requirement' => 3,
                'temperature_min' => 18,
                'temperature_max' => 28,
                'humidity_level' => 65,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau drainant',
                'difficulty_level' => 3,
                'is_indoor' => true,
                'is_toxic' => true,
                'max_height' => 150,
                'tags' => ['Grand format', 'Tropical', 'Feuillage spectaculaire'],
            ],
            // 10. Scindapsus pictus
            [
                'name' => 'Scindapsus marbré',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Scindapsus',
                'species' => 'pictus',
                'scientific_name' => 'Scindapsus pictus',
                'description' => 'Feuilles vertes avec taches argentées. Croissance lente mais très décoratives.',
                'purchase_date' => '15/09/2023',
                'location' => 'Étagère salon',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 24,
                'humidity_level' => 55,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau universel',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'tags' => ['Feuillage marbré', 'Compact', 'Décoratif'],
            ],
            // 11. Lavandula angustifolia
            [
                'name' => 'Lavande blanche',
                'family' => 'Lamiaceae',
                'subfamily' => 'Nepetoideae',
                'genus' => 'Lavandula',
                'species' => 'angustifolia',
                'variety' => 'alba',
                'scientific_name' => 'Lavandula angustifolia',
                'description' => 'Fleurs blanches parfumées. Plante méditerranéenne, très résistante et aromatique.',
                'purchase_date' => '18/05/2023',
                'location' => 'Balcon',
                'light_requirement' => 5,
                'temperature_min' => 10,
                'temperature_max' => 25,
                'humidity_level' => 40,
                'watering_frequency' => 4,
                'soil_type' => 'Terreau léger drainant',
                'difficulty_level' => 1,
                'is_indoor' => false,
                'is_outdoor' => true,
                'is_toxic' => false,
                'tags' => ['Floraison', 'Aromatique', 'Méditerranéenne'],
            ],
            // 12. Rosmarinus officinalis
            [
                'name' => 'Romarin',
                'family' => 'Lamiaceae',
                'subfamily' => 'Nepetoideae',
                'genus' => 'Rosmarinus',
                'species' => 'officinalis',
                'scientific_name' => 'Rosmarinus officinalis',
                'description' => 'Herbe aromatique persistante. Utilisable en cuisine, très résistante.',
                'purchase_date' => '12/06/2023',
                'purchase_place' => 'Marché',
                'location' => 'Balcon cuisine',
                'light_requirement' => 5,
                'temperature_min' => 5,
                'temperature_max' => 25,
                'humidity_level' => 40,
                'watering_frequency' => 4,
                'soil_type' => 'Terreau cactus',
                'difficulty_level' => 1,
                'is_indoor' => false,
                'is_outdoor' => true,
                'is_toxic' => false,
                'tags' => ['Aromatique', 'Culinaire', 'Méditerranéenne'],
            ],
            // 13. Rosa × damascena
            [
                'name' => 'Rose de Damas',
                'family' => 'Rosaceae',
                'subfamily' => 'Rosoideae',
                'genus' => 'Rosa',
                'species' => 'damascena',
                'scientific_name' => 'Rosa × damascena',
                'description' => 'Rose classique rouge pourpre très parfumée. Idéale pour le jardin, longue floraison.',
                'purchase_date' => '20/03/2023',
                'location' => 'Jardin',
                'light_requirement' => 5,
                'temperature_min' => 5,
                'temperature_max' => 30,
                'humidity_level' => 50,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau riche pour roses',
                'difficulty_level' => 2,
                'is_indoor' => false,
                'is_outdoor' => true,
                'is_toxic' => false,
                'flowering_season' => 'Printemps-Été',
                'tags' => ['Floraison', 'Rose', 'Parfumée'],
            ],
            // 14. Cactus cereus repandus
            [
                'name' => 'Cactus colonne',
                'family' => 'Cactaceae',
                'subfamily' => 'Cactoideae',
                'genus' => 'Cereus',
                'species' => 'repandus',
                'scientific_name' => 'Cereus repandus',
                'description' => 'Grand cactus colonnaire. Fleurs blanches en été. Très facile et peu d\'entretien.',
                'purchase_date' => '05/01/2022',
                'location' => 'Fenêtre sud',
                'light_requirement' => 5,
                'temperature_min' => 5,
                'temperature_max' => 30,
                'humidity_level' => 30,
                'watering_frequency' => 5,
                'soil_type' => 'Terreau cactus',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_outdoor' => true,
                'is_toxic' => false,
                'max_height' => 200,
                'tags' => ['Succulente', 'Très facile', 'Xérophyte'],
            ],
            // 15. Aloe vera
            [
                'name' => 'Aloe vera',
                'family' => 'Asphodelaceae',
                'subfamily' => 'Asphodeloideae',
                'genus' => 'Aloe',
                'species' => 'barbadensis',
                'scientific_name' => 'Aloe barbadensis',
                'description' => 'Plante succulente pour soins. Gel utilisé en cosmétique et médecine. Très rustique.',
                'purchase_date' => '08/04/2023',
                'location' => 'Fenêtre sud',
                'light_requirement' => 5,
                'temperature_min' => 10,
                'temperature_max' => 30,
                'humidity_level' => 35,
                'watering_frequency' => 5,
                'soil_type' => 'Terreau cactus',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_outdoor' => true,
                'is_toxic' => false,
                'tags' => ['Succulente', 'Médicinale', 'Très facile'],
            ],
            // 16. Clivia miniata
            [
                'name' => 'Lis de Clivia',
                'family' => 'Amaryllidaceae',
                'subfamily' => 'Amaryllidoideae',
                'genus' => 'Clivia',
                'species' => 'miniata',
                'scientific_name' => 'Clivia miniata',
                'description' => 'Fleurs orange en forme de trompette. Beauté classique, longue durée de vie.',
                'purchase_date' => '10/08/2022',
                'location' => 'Salon ombre',
                'light_requirement' => 2,
                'temperature_min' => 12,
                'temperature_max' => 22,
                'humidity_level' => 55,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau riche',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => true,
                'flowering_season' => 'Printemps',
                'tags' => ['Floraison', 'Orange', 'Longévité'],
            ],
            // 17. Spathiphyllum wallisii
            [
                'name' => 'Lis de paix',
                'family' => 'Araceae',
                'subfamily' => 'Aroideae',
                'genus' => 'Spathiphyllum',
                'species' => 'wallisii',
                'scientific_name' => 'Spathiphyllum wallisii',
                'description' => 'Fleurs blanches pures. Plante ultra-facile, tolère l\'ombre totale. Purifie l\'air.',
                'purchase_date' => '25/11/2022',
                'location' => 'Bureau ombre',
                'light_requirement' => 1,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 60,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau riche',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Floraison', 'Très facile', 'Purifiante'],
            ],
            // 18. Begonia maculata
            [
                'name' => 'Bégonia ailé',
                'family' => 'Begoniaceae',
                'subfamily' => 'Begonioideae',
                'genus' => 'Begonia',
                'species' => 'maculata',
                'scientific_name' => 'Begonia maculata',
                'description' => 'Feuilles vertes tachetées de blanc. Fleurs rouges. Feuillage et floraison décoratives.',
                'purchase_date' => '15/07/2023',
                'location' => 'Salon lumineux',
                'light_requirement' => 3,
                'temperature_min' => 16,
                'temperature_max' => 24,
                'humidity_level' => 60,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau léger riche',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Feuillage marbré', 'Floraison', 'Tropical'],
            ],
            // 19. Dionaea muscipula
            [
                'name' => 'Piège à mouche',
                'family' => 'Droseraceae',
                'subfamily' => null,
                'genus' => 'Dionaea',
                'species' => 'muscipula',
                'scientific_name' => 'Dionaea muscipula',
                'description' => 'Plante carnivore fascinante. Pièges actifs qui se ferment en 0.1 seconde. Curiosité botanique.',
                'purchase_date' => '20/06/2023',
                'location' => 'Fenêtre lumineuse',
                'light_requirement' => 5,
                'temperature_min' => 15,
                'temperature_max' => 24,
                'humidity_level' => 70,
                'watering_frequency' => 2,
                'soil_type' => 'Tourbe acide',
                'difficulty_level' => 4,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Carnivore', 'Curiosité', 'Humidité'],
            ],
            // 20. Nepenthes alata
            [
                'name' => 'Plante cruche',
                'family' => 'Nepenthaceae',
                'subfamily' => null,
                'genus' => 'Nepenthes',
                'species' => 'alata',
                'scientific_name' => 'Nepenthes alata',
                'description' => 'Plante carnivore tropicale avec pièges en forme de cruches. Floraison spectaculaire.',
                'purchase_date' => '10/08/2023',
                'location' => 'Serre humide',
                'light_requirement' => 4,
                'temperature_min' => 20,
                'temperature_max' => 28,
                'humidity_level' => 80,
                'watering_frequency' => 2,
                'soil_type' => 'Sphaigne',
                'difficulty_level' => 4,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Carnivore', 'Tropical', 'Humidité extrême'],
            ],
            // 21. Hoya kerrii
            [
                'name' => 'Plante cœur',
                'family' => 'Apocynaceae',
                'subfamily' => 'Asclepiadoideae',
                'genus' => 'Hoya',
                'species' => 'kerrii',
                'scientific_name' => 'Hoya kerrii',
                'description' => 'Petites feuilles en forme de cœur. Plante succulente compacte, très mignonne.',
                'purchase_date' => '14/02/2023',
                'location' => 'Rebord fenêtre',
                'light_requirement' => 4,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 45,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau succulente',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Succulente', 'Compact', 'Cœur'],
            ],
            // 22. Hoya carnosa
            [
                'name' => 'Fleur de porcelaine',
                'family' => 'Apocynaceae',
                'subfamily' => 'Asclepiadoideae',
                'genus' => 'Hoya',
                'species' => 'carnosa',
                'scientific_name' => 'Hoya carnosa',
                'description' => 'Grappes de fleurs roses cireuses très parfumées. Grimpante facile, longévité remarquable.',
                'purchase_date' => '05/05/2022',
                'location' => 'Treillage salon',
                'light_requirement' => 4,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 50,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau léger riche',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Floraison', 'Plante grimpante', 'Parfumée'],
            ],
            // 23. Vriesea splendens
            [
                'name' => 'Broméliacée épée',
                'family' => 'Bromeliaceae',
                'subfamily' => 'Tillandsioideae',
                'genus' => 'Vriesea',
                'species' => 'splendens',
                'scientific_name' => 'Vriesea splendens',
                'description' => 'Inflorescence rouge écarlate spectaculaire en forme d\'épée. Floraison longue.',
                'purchase_date' => '22/09/2023',
                'location' => 'Table basse',
                'light_requirement' => 3,
                'temperature_min' => 18,
                'temperature_max' => 28,
                'humidity_level' => 70,
                'watering_frequency' => 2,
                'soil_type' => 'Écorce épiphyte',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Floraison', 'Tropical', 'Broméliacée'],
            ],
            // 24. Tillandsia usneoides
            [
                'name' => 'Barbe de vieillard',
                'family' => 'Bromeliaceae',
                'subfamily' => 'Tillandsioideae',
                'genus' => 'Tillandsia',
                'species' => 'usneoides',
                'scientific_name' => 'Tillandsia usneoides',
                'description' => 'Plante sans racine, épiphyte. Aucun terreau requis, juste brumisations régulières.',
                'purchase_date' => '30/06/2023',
                'location' => 'Suspendu fenêtre',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 75,
                'watering_frequency' => 2,
                'soil_type' => 'Aucun (épiphyte)',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_outdoor' => true,
                'is_toxic' => false,
                'tags' => ['Épiphyte', 'Sans racine', 'Aérien'],
            ],
            // 25. Paphiopedilum rothschildianum
            [
                'name' => 'Sabot de Vénus',
                'family' => 'Orchidaceae',
                'subfamily' => 'Cypripedioideae',
                'genus' => 'Paphiopedilum',
                'species' => 'rothschildianum',
                'scientific_name' => 'Paphiopedilum rothschildianum',
                'description' => 'Orchidée exotique spectaculaire, très rare. Labelle en forme de sabot distinctif.',
                'purchase_date' => '10/12/2022',
                'location' => 'Serre orchidée',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 22,
                'humidity_level' => 70,
                'watering_frequency' => 2,
                'soil_type' => 'Écorce orchidée premium',
                'difficulty_level' => 4,
                'is_indoor' => true,
                'is_toxic' => false,
                'tags' => ['Orchidée', 'Rare', 'Exotique'],
            ],
            // 26. Dracaena draco
            [
                'name' => 'Dragonnier',
                'family' => 'Asparagaceae',
                'subfamily' => 'Nolinoideae',
                'genus' => 'Dracaena',
                'species' => 'draco',
                'scientific_name' => 'Dracaena draco',
                'description' => 'Arbre spectaculaire à croissance lente. Feuilles bleu-gris, aspect architectural imposant.',
                'purchase_date' => '15/11/2021',
                'location' => 'Coin séjour',
                'light_requirement' => 3,
                'temperature_min' => 12,
                'temperature_max' => 25,
                'humidity_level' => 50,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau universel',
                'difficulty_level' => 1,
                'is_indoor' => true,
                'max_height' => 120,
                'tags' => ['Grand format', 'Architectural', 'Facile'],
            ],
            // 27. Anthurium clarinervium
            [
                'name' => 'Anthurium noir',
                'family' => 'Araceae',
                'subfamily' => 'Aroideae',
                'genus' => 'Anthurium',
                'species' => 'clarinervium',
                'scientific_name' => 'Anthurium clarinervium',
                'description' => 'Feuilles noires veloutées avec nervures blanches éclatantes. Très rare et précieux.',
                'purchase_date' => '20/01/2023',
                'location' => 'Collection spéciale',
                'light_requirement' => 3,
                'temperature_min' => 18,
                'temperature_max' => 28,
                'humidity_level' => 75,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau riche aéré',
                'difficulty_level' => 3,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Feuillage noir', 'Rare', 'Tropical'],
            ],
            // 28. Monstera deliciosa var. borsigiana
            [
                'name' => 'Monstera Albo',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Monstera',
                'species' => 'deliciosa',
                'variety' => 'borsigiana',
                'cultivar' => 'Albo Variegata',
                'scientific_name' => 'Monstera deliciosa var. borsigiana',
                'description' => 'Monstera panachée de blanc, très rare. Feuilles partiellement blanches avec perforations.',
                'purchase_date' => '08/07/2023',
                'location' => 'Collection premium',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 25,
                'humidity_level' => 55,
                'watering_frequency' => 3,
                'soil_type' => 'Terreau riche drainant',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'is_toxic' => true,
                'tags' => ['Panachée', 'Rare', 'Collection'],
            ],
            // 29. Rhaphidophora tetrasperma var. minima
            [
                'name' => 'Mini Monstera Ginny',
                'family' => 'Araceae',
                'subfamily' => 'Monsteroideae',
                'genus' => 'Rhaphidophora',
                'species' => 'tetrasperma',
                'variety' => 'minima',
                'scientific_name' => 'Rhaphidophora tetrasperma',
                'description' => 'Version ultra-compacte miniature. Parfaite pour les petits espaces et vitrines.',
                'purchase_date' => '12/09/2023',
                'location' => 'Terrarium',
                'light_requirement' => 3,
                'temperature_min' => 15,
                'temperature_max' => 24,
                'humidity_level' => 60,
                'watering_frequency' => 2,
                'soil_type' => 'Terreau universel',
                'difficulty_level' => 2,
                'is_indoor' => true,
                'tags' => ['Compact', 'Miniature', 'Collection'],
            ],
            // 30. Stenorrhynchos speciosus
            [
                'name' => 'Orchidée crête',
                'family' => 'Orchidaceae',
                'subfamily' => 'Epidendroideae',
                'genus' => 'Stenorrhynchos',
                'species' => 'speciosus',
                'scientific_name' => 'Stenorrhynchos speciosus',
                'description' => 'Orchidée délicieuse avec inflorescence rouge orangée en spirale. Floraison hivernale.',
                'purchase_date' => '25/10/2023',
                'location' => 'Serre froide',
                'light_requirement' => 4,
                'temperature_min' => 12,
                'temperature_max' => 20,
                'humidity_level' => 65,
                'watering_frequency' => 2,
                'soil_type' => 'Écorce orchidée',
                'difficulty_level' => 3,
                'is_indoor' => true,
                'is_toxic' => false,
                'flowering_season' => 'Automne-Hiver',
                'tags' => ['Orchidée', 'Floraison hivernale', 'Spectaculaire'],
            ],
        ];

        // Récupérer tous les tags disponibles
        $allTags = Tag::all();
        $tagsByName = $allTags->keyBy('name');

        // Créer les plantes
        foreach ($plants as $plantData) {
            $tags = $plantData['tags'] ?? [];
            unset($plantData['tags']);

            $plant = Plant::create($plantData);

            // Associer les tags
            if (!empty($tags)) {
                $tagIds = [];
                foreach ($tags as $tagName) {
                    if (isset($tagsByName[$tagName])) {
                        $tagIds[] = $tagsByName[$tagName]->id;
                    }
                }
                if (!empty($tagIds)) {
                    $plant->tags()->sync($tagIds);
                }
            }

            // Générer une couleur de placeholder pour chaque plante
            $this->generatePlaceholderImage($plant);
        }

        $this->command->info('✅ 30 plantes complètes créées avec succès!');
    }

    /**
     * Générer une image placeholder basée sur la famille de la plante
     */
    private function generatePlaceholderImage(Plant $plant): void
    {
        // Couleurs par famille
        $familyColors = [
            'Orchidaceae' => '#8B4789',
            'Araceae' => '#2D5016',
            'Asparagaceae' => '#556B2F',
            'Lamiaceae' => '#8B7355',
            'Rosaceae' => '#E4007C',
            'Cactaceae' => '#90EE90',
            'Asphodelaceae' => '#9ACD32',
            'Amaryllidaceae' => '#FFB6C1',
            'Droseraceae' => '#8B0000',
            'Nepenthaceae' => '#228B22',
            'Apocynaceae' => '#FFD700',
            'Bromeliaceae' => '#FF6347',
            'Begoniaceae' => '#FF69B4',
            'Moraceae' => '#8FBC8F',
            'Marantaceae' => '#CD853F',
        ];

        $color = $familyColors[$plant->family] ?? '#808080';
        $hexColor = str_replace('#', '', $color);

        // Générer une image placeholder via service en ligne
        $width = 400;
        $height = 400;
        $placeholder = "https://via.placeholder.com/{$width}x{$height}/{$hexColor}/FFFFFF?text=" . urlencode($plant->name);

        // Télécharger et stocker l'image si possible
        try {
            $imageContent = file_get_contents($placeholder);
            if ($imageContent) {
                $filename = 'plants/' . strtolower(str_replace(' ', '-', $plant->name)) . '.jpg';
                Storage::disk('public')->put($filename, $imageContent);
                $plant->update(['main_photo' => $filename]);
            }
        } catch (\Exception $e) {
            // En cas d'erreur, on laisse sans image
            $this->command->warn("⚠️  Image non générée pour {$plant->name}");
        }
    }
}
